### ISSUE TITLE
What purpose to add ASSETS_LINK in Metronic.php?

### ISSUE THREAD

**Issue by hexl** [dlds/yii2-metronic#1]

**Comment by jirisvoboda** [comment]
This is directory path where Metronic assets (your metronic theme css and js files) will be linked to using symbolic link.

**Comment by hexl** [comment]
But https://github.com/dlds/yii2-metronic/blob/master/Metronic.php#L27 has compile error

**Comment by ofavor** [comment]
I encouter the compile error, too.
I have to modify the code as following:

``` php
define('METRONIC_ASSETS_LINK', __DIR__.'/assets');

/**
 * This is the class of Metronic Component
 */
class Metronic extends \yii\base\Component {

    /**
     * @var AssetBundle
     */
    public static $assetsBundle;

    /**
     * Assets link
     */
    const ASSETS_LINK = METRONIC_ASSETS_LINK;
...
```

**Comment by jirisvoboda** [comment]
Hey,

documentation is still in progress but the error you posted here can be solved by updating your PHP version to 5.6.

**Comment by jirisvoboda** [comment]
to define from where the assets files should be linked to use this configuration in your config.php

```
'components' => [
   // ...
   'metronic' => [
      'resources' => __DIR__.'/../../common/vendor/metronic',
   ],
   // ...
],
```

In this example all medtronic assets files are stored in common/vendor/metronic directory

**Comment by lutek** [comment]
Hi, 
i think better if will be made it compatible with 5.4
