### ISSUE TITLE
last yii2-bootstrap (bootstrap 4.1.1)

### ISSUE THREAD

**Issue by paskuale75** [dlds/yii2-metronic#23]
I've upgraded yii2-bootstrap and all layout be corrupted... maybe last bootstrap version (4.1.1) ?
Thanks

**Comment by svobik7** [comment]
Hi paskuale75, unfortunately I wont update my package to support new boostratp version. Tested version is 3.3.7.

Feel free to fork an update.

**Comment by paskuale75** [comment]
Ok, unfortunately, they have updated the yii2 framework and together with the bootstrap version, thanks too
